version: '2'
services:
  app: &app_base
    build: .
    ports:
      - 9998:9998
    command: bundle exec rails s -p 9998 -b '0.0.0.0'
    volumes:
      - .:/usr/src/nippo
    links:
      - mysql
    tty: true
    stdin_open: true
  spring:
    <<: *app_base
    command: "bundle exec spring server"
    ports: []
    tty: false
    stdin_open: false
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes_from:
      - datastore
    ports:
      - "3306:3306"
  datastore:
    image: "busybox"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
